### ISSUE TITLE
Why not a C++?

### ISSUE THREAD

**Issue by Koalamana9** [vagrod/zara#3]
How difficult would it be to convert the entire codebase to C++? The compiled library can be linked to any game engine.

**Comment by vagrod** [comment]
Hi! I never had an interest in C++, so that's basically the answer -- but I ported Zara to Rust a while ago, keeping all the functionality of the original, and theoretically you could use it in any C++ project, there are many examples of how to call Rust code from C/C++ on the interwebs.
